image: google/cloud-sdk:latest

stages:
  - checkout
  - build
  - deploy

variables:
  PROJECT_ID: "academic-atlas-475811-c5"
  REGION: "us-central1"
  REPO: "my-repo"
  REGISTRY: "us-central1-docker.pkg.dev"
  CLUSTER: "my-cluster"

checkout_code:
  stage: checkout
  script:
    - echo "Code Checked out.."

build_docker_image:
  stage: build
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$GCP_SA_KEY" | base64 -d > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud auth configure-docker $REGISTRY
    # Install Docker here if it's not already available
    - apt-get update && apt-get install -y docker.io
  script:
    - docker build -t $REGISTRY/$PROJECT_ID/$REPO/mlops-app:latest .
    - docker push $REGISTRY/$PROJECT_ID/$REPO/mlops-app:latest

deploy_to_gke:
  stage: deploy
  before_script:
    - echo "$GCP_SA_KEY" | base64 -d > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud auth configure-docker $REGISTRY
  script:
    - gcloud container clusters get-credentials $CLUSTER --region $REGION --project $PROJECT_ID
    - kubectl apply -f kubernetes-deployment.yaml